#!/usr/bin/env bash

set -eo pipefail

pushd "$(mktemp -d)"
    curl -sL "https://github.com/facebook/infer/releases/download/v${INFER_VERSION}/infer-linux64-v${INFER_VERSION}.tar.xz" | tar xJ
    cd "infer-linux64-v${INFER_VERSION}/"
    ./build-infer.sh --yes java
    export PATH="${PWD}/infer/bin:${PATH}"
popd

infer --fail-on-issue -- gradle build
