#!/usr/bin/env bash

set -e
set -u
set -o pipefail

INFER_DIR="${INFER_DIRECTORY}/infer-linux64-v${INFER_VERSION}"
INFER_BIN="${INFER_DIRECTORY}/infer-linux64-v${INFER_VERSION}/infer/bin"

if [[ ! -x "${INFER_BIN}/infer" ]]
then
	pushd "${INFER_DIRECTORY}"
	curl -sL "https://github.com/facebook/infer/releases/download/v${INFER_VERSION}/infer-linux64-v${INFER_VERSION}.tar.xz" | tar xJ
	cd "infer-linux64-v${INFER_VERSION}/"
	./build-infer.sh --yes java
	popd
fi

export PATH="${INFER_BIN}:${PATH}"
infer --fail-on-issue -- gradle build
