#!/usr/bin/env bash

set -e
set -o pipefail

readonly DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)

docker_run() {
    docker run --detach rxb '-Dport=8888' '-Ddestination=255.255.255.255' '-DdestinationPort=8888' "$@"
}

class=$1

containers=()
container=$(docker_run 'org.junit.runner.JUnitCore' "$class")
containers+=($container)

docker_run "$class"

if ! docker wait "${containers[@]}" | awk '/1/ { exit 1 }'
then
    set -x
    for container in "${containers[@]}"
    do
        docker logs "$container"
    done
    exit 1
fi
