#!/usr/bin/env bash

set -eo pipefail

readonly DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)

docker_run() {
    docker run --detach rxb '-Ddestination=255.255.255.255' '-Dport=8888' "$@"
}

test_class() {
    local class=$1
    local network_command=${2:-:}

    containers=()
    for _ in {1..5}
    do
        container=$(docker_run 'org.junit.runner.JUnitCore' "$class")
        DOCKER_IFACE=$("$DIR/veth" "$container") bash -xc "$network_command"
        containers+=($container)
    done

    docker_run "$class"

    if ! docker wait "${containers[@]}" | awk '/1/ { exit 1 }'
    then
        set -x
        for container in "${containers[@]}"
        do
            docker logs "$container"
        done
        return 1
    fi
}

test_class rx.broadcast.integration.BasicOrderUdpBroadcastTest
