#!/usr/bin/env bash

set -e
set -o pipefail

readonly DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)

docker_run() {
    docker run --net=host --detach rxb '-Ddestination=ff02::1' '-Dport=8888' "$@"
}

class=$1
network_command=${2:-:}

containers=()
for _ in {1..5}
do
    container=$(docker_run 'org.junit.runner.JUnitCore' "$class")
    DOCKER_IFACE=$("$DIR/veth" "$container") bash -xc "shopt -s extglob; $network_command"
    containers+=($container)
done

containers+=($(docker_run "$class"))

if ! docker wait "${containers[@]}" | awk '/1/ { exit 1 }'
then
    set -x
    for container in "${containers[@]}"
    do
        docker logs "$container"
    done
    exit 1
fi
