#!/usr/bin/env bash

set -eo pipefail

readonly DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)

container=$1
ifindex=$(sudo nsenter --net="$(docker inspect --format='{{.NetworkSettings.SandboxKey}}' "$container")" ethtool -S eth0 | \
    awk -f "$DIR/nicstats.awk")
ip link list | awk -v ifindex="$ifindex" -f "$DIR/ip.awk"
